-- 参数配置类型
INSERT INTO sys_config_type(config_type_id, config_type_name, config_type_code, config_type, visible_flag, config_type_sort, del_flag, create_time) VALUES (1, '系统配置', 'sys_config', 1, true, 1.00, 'N', now());
INSERT INTO sys_config_type(config_type_id, config_type_name, config_type_code, config_type, visible_flag, config_type_sort, del_flag, create_time) VALUES (2, '鉴权配置', 'auth_config', 1, true, 1.00, 'N', now());
INSERT INTO sys_config_type(config_type_id, config_type_name, config_type_code, config_type, visible_flag, config_type_sort, del_flag, create_time) VALUES (3, '文件配置', 'file_config', 1, true, 1.00, 'N', now());

-- 系统配置
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (1, 'sys_config', '系统配置是否已经初始化的标识', 'SYS_CONFIG_INIT_FLAG', false, 1, true, 1.00, 'N', now());
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (2, 'sys_config', '不用过滤的URL', 'SYS_NONE_SECURITY_URLS', '/favicon.ico,/swagger-ui/**', 1, true, 1.00, 'N', now());
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (3, 'file_config', '服务默认部署的环境地址', 'SYS_SERVER_DEPLOY_HOST', 'http://127.0.0.1:11938', 1, true, 1.00, 'N', now());
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (4, 'auth_config', 'Session过期时间(秒)', 'SYS_SESSION_EXPIRED_SECONDS', '3600', 1, true, 1.00, 'N', now());
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (5, 'auth_config', '系统默认密码', 'SYS_DEFAULT_PASSWORD', '123456789', 1, true, 1.00, 'N', now());
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (6, 'auth_config', '用于auth模块权限校验的JWT失效时间(秒)', 'SYS_AUTH_JWT_TIMEOUT_SECONDS', '604800', 1, true, 1.00, 'N', now());
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (7, 'auth_config', '密码最大重试次数', 'SYS_LOGIN_MAX_ERROR_LOGIN_COUNT', '5', 1, true, 1.00, 'N', now());
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (8, 'auth_config', '密码策略:口令最小长度', 'SYS_LOGIN_MIN_PASSWORD_LENGTH', '6', 1, true, 1.00, 'N', now());
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (9, 'auth_config', '密码策略:最少特殊符号数量', 'SYS_LOGIN_PASSWORD_MIN_SPECIAL_SYMBOL_COUNT', '0', 1, true, 1.00, 'N', now());
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (10, 'auth_config', '密码策略:最少大写字母数量', 'SYS_LOGIN_PASSWORD_MIN_UPPER_CASE_COUNT', '0', 1, true, 1.00, 'N', now());
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (11, 'auth_config', '密码策略:最少小写字母数量', 'SYS_LOGIN_PASSWORD_MIN_LOWER_CASE_COUNT', '0', 1, true, 1.00, 'N', now());
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (12, 'auth_config', '密码策略:最少数字符号的数量', 'SYS_LOGIN_PASSWORD_MIN_NUMBER_COUNT', '0', 1, true, 1.00, 'N', now());
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (13, 'auth_config', '密码策略:最少多久更新一次密码(天)', 'SYS_LOGIN_PASSWORD_MIN_UPDATE_DAYS', '180', 1, true, 1.00, 'N', now());
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (14, 'auth_config', '密码策略:修改密码时,不能和历史密码重复的次数', 'SYS_LOGIN_PASSWORD_MIN_CANT_REPEAT_TIMES', '0', 1, true, 1.00, 'N', now());
insert into sys_config (config_id, config_type_code, config_name, config_code, config_value, config_type, visible_flag, config_sort, del_flag, create_time) values (15, 'auth_config', 'auth认证用的JWT秘钥,用于校验登录token', 'SYS_AUTH_JWT_SECRET', 'D9KbZxFM5Xm1SNxQ1LvO5m36DqvHFH', 1, true, 1.00, 'N', now());
